FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar archivos de la aplicación
COPY . .

# Crear directorios necesarios y establecer permisos
RUN mkdir -p /app/downloads /app/temp \
    && chmod 755 /app/downloads \
    && chmod 755 /app/temp

# Exponer el puerto
EXPOSE 5000

# Comando para ejecutar la aplicación con Gunicorn
CMD ["gunicorn", "--workers=4", "--bind=0.0.0.0:5000", "wsgi:app"]