version: '3'

services:
  pdf-downloader-api:
    build:
      context: .
      dockerfile: Dockerfile.linux
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./temp:/app/temp
    restart: unless-stopped
    environment:
      - FLASK_ENV=production