[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn wsgi:app"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 300

[variables]
FLASK_ENV = "production"
PORT = "8080"